project:
  type: website

website:
  title: "Fluid Dynamics and Cell Mechanics"

  navbar:
    left:

      - text: "Fluid Dynamics"
        menu:
          - href: NotesIntroNavierStokes.qmd
            text: Introduction to the Navier-Stokes equation

          - href: FluidMechanicsProblemClass.qmd
            text: Fluid dynamics problem class

          - href: LowRe.qmd
            text: A blink of life at low Reynolds number

          - href: ComplexFluids.qmd
            text: An introduction to complex (bio)fluids

      - text: "Cell Mechanics"
        menu:
          - href: OsmoticPressure.qmd
            text: Red blood cells, osmotic pressure and cell volume regulation

          - href: MembraneElasticity.qmd
            text: Membrane elasticity

          - href: MembraneMechanicsProblemClass.qmd
            text: Membrane elasticity problem class

          - href: RBCAggregation.qmd
            text: Aggregation of microscopic particles



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true