project:
  type: website

website:
  title: "Fluid Dynamics and Cell Mechanics"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: NotesIntroNavierStokes.qmd
        text: Introduction to the Navier-Stokes Equation

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



