project:
  type: website

website:
  title: "Fluid Dynamics and Cell Mechanics"
  navbar:
    left:
      - href: NotesIntroNavierStokes.qmd
        text: Introduction to the Navier-Stokes Equation

      - href: FluidMechanicsProblemClass.qmd
        text: Fluid Dynamics Problem Class

      - href: LowRe.qmd
        text: A blink of life at low Reynolds number

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



